"""Generate src/unicode_tables.h: the exact character classes BERT's BasicTokenizer uses
(control / whitespace / punctuation) plus a lowercase+strip-accents map, so the C
tokenizer reproduces HuggingFace WordPiece tokenization byte-for-byte."""
import unicodedata, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = []
LIM = 0x30000

def is_ws(c):
    return c in " \t\n\r" or unicodedata.category(c) == "Zs"
def is_ctrl(c):
    if c in "\t\n\r": return False
    return unicodedata.category(c) in ("Cc", "Cf")
def is_punct(cp, c):
    if (33 <= cp <= 47) or (58 <= cp <= 64) or (91 <= cp <= 96) or (123 <= cp <= 126): return True
    return unicodedata.category(c).startswith("P")

ws, ctrl, punct = [], [], []
for cp in range(LIM):
    c = chr(cp)
    if is_ws(c): ws.append(cp)
    if is_ctrl(c): ctrl.append(cp)
    if is_punct(cp, c): punct.append(cp)

def ranges(lst):
    r = []
    for cp in lst:
        if r and r[-1][1] == cp - 1: r[-1][1] = cp
        else: r.append([cp, cp])
    return r

def emit_ranges(name, lst):
    rr = ranges(lst)
    out.append(f"static const uint32_t {name}[][2] = {{" + ",".join(f"{{{a:#x},{b:#x}}}" for a, b in rr) + "};")
    out.append(f"#define {name.upper()}_N {len(rr)}")

emit_ranges("uni_ws", ws); emit_ranges("uni_ctrl", ctrl); emit_ranges("uni_punct", punct)

# lowercase + strip accents map for non-ASCII BMP codepoints (BERT: lower() then NFD, drop Mn)
m = []
for cp in range(0x80, 0x10000):
    c = chr(cp)
    cat = unicodedata.category(c)
    if cat.startswith(("L", "M", "N")) is False and cat != "Mn":
        continue
    low = c.lower()
    nfd = unicodedata.normalize("NFD", low)
    res = "".join(ch for ch in nfd if unicodedata.category(ch) != "Mn")
    if res != c:
        m.append((cp, res))
out.append("typedef struct { uint32_t cp; const char *rep; } UniMap;")
out.append("static const UniMap uni_lower_map[] = {" + ",".join(
    "{%#x,\"%s\"}" % (cp, "".join("\\x%02x" % b for b in rep.encode("utf-8"))) for cp, rep in m) + "};")
out.append(f"#define UNI_LOWER_MAP_N {len(m)}")
open(os.path.join(ROOT, "src", "unicode_tables.h"), "w").write("/* generated by scripts/gen_unicode.py */\n#include <stdint.h>\n" + "\n".join(out) + "\n")
print("ws ranges", len(ranges(ws)), "ctrl", len(ranges(ctrl)), "punct", len(ranges(punct)), "lower map", len(m))
