# (question, list of acceptable answer substrings (lowercase) -- any match counts)
TESTS = [
    ("Who is the king of Dutch Robloxia?", ["nicholas goudhof v"]),
    ("What is the capital of Dutch Robloxia?", ["dunhag"]),
    ("Who is the prime minister?", ["henry barkworth"]),
    ("When was King Nicholas born?", ["19 aug 1984", "august 19th 1984"]),
    ("Where was Nicholas Goudhof born?", ["amsterdam"]),
    ("Who is the queen?", ["eloise goudhof ii"]),
    ("Where was Queen Eloise born?", ["utrecht"]),
    ("What is the political capital?", ["oysterdam"]),
    ("What are the branches of the military?", ["royal army", "four"]),
    ("Who is the minister of finance?", ["leonard ii"]),
    ("Who is the minister of foreign affairs?", ["daverammstein44"]),
    ("Who is the minister of defence?", ["bjorn"]),
    ("What is the national anthem?", ["wilhelmus"]),
    ("When was the kingdom founded?", ["october 2022", "oct 2022"]),
    ("What is the Buizerd?", ["plane", "dc-3"]),
    ("Where is the Buizerd located?", ["heuvelmeer"]),
    ("What is the Eloise Express?", ["train"]),
    ("When was the Eloise Express built?", ["1918"]),
    ("Where does the Eloise Express depart from?", ["silverrail station"]),
    ("Who bought the island of Vaderveen?", ["nicholas goudhof iv"]),
    ("When was Vaderveen bought?", ["1989"]),
    ("Who was the overseer of Vaderveen?", ["jack houtman"]),
    ("When did Jack Houtman die?", ["10 april 1998", "1998"]),
    ("Where was Jack Houtman born?", ["australia"]),
    ("What is Huis Theerots?", ["teahouse"]),
    ("What is Huis Duurn?", ["exile home", "german emperor", "estate"]),
    ("What is the motto of Dutch Robloxia?", ["leve goudhof"]),
    ("What is the highest rank in the Royal Navy?", ["admiral"]),
    ("What is the lowest rank in the Royal Army?", ["private"]),
    ("Which Roblox user plays King Nicholas?", ["nickiscoolinroblox"]),
    ("Who plays the Pope?", ["taskapro1001"]),
    ("When was the pope born?", ["30.4.1977", "30. april 1977"]),
    ("How tall is King Nicholas?", ["184"]),
    ("What is the Mosselman?", ["ship", "water vessel"]),
    ("Which car is the most common in Dutch Robloxia?", ["plymouth"]),
    ("What is Angel Island known for?", ["angel statue"]),
    ("Who is Emma Bloem?", ["mistress", "beauty"]),
    ("Where was Emma Bloem born?", ["bremen"]),
    ("Who is the heir to the throne?", ["friso"]),
    ("When was Prince Friso born?", ["2005"]),
    ("What is the 11th Airmobile Brigade?", ["paratroop"]),
    ("What is the Royal Guard?", ["elite", "personal guard", "escort"]),
    ("Which regions have governors?", ["heuvelmeer"]),
    ("Where is the Consulate?", ["london"]),
    ("What is Silver Wings Air?", ["aviation"]),
    ("Is North Korea an ally?", ["allied", "ally"]),
    ("Who composed the songs of the kingdom?", ["nicholas goudhof v"]),
    ("What is the first law of the realm?", ["display name"]),
    ("How many laws are there?", ["eight", "8"]),
    ("How do I join the military?", ["#military-recruitment", "military-recruitment"]),
    ("Who programmed the wiki?", ["leonard ii"]),
    ("What is the Peace Castle?", ["diplomacy", "peace treaties", "castle in dunhag"]),
    ("What is Firewood Forest used for?", ["military testing"]),
    ("Which island is inspired by the Wadden Islands?", ["hendrikdam"]),
    ("What year is the MG MGA Roadster from?", ["1955", "50s"]),
    ("What type of government does the kingdom have?", ["semi-constitutional monarchy"]),
    ("Who is Krol van Male?", ["king of the united kingdom", "upper class citizen"]),
    ("Where does the king live?", ["coastburgh castle"]),
    ("How old is the king?", ["39"]),
    ("Who is the CEO of Goudhof Enterprises?", ["nicholas goudhof v"]),
    ("What is Dutch Robloxia?", ["monarchy", "kingdom", "country"]),
    ("What is the Royal Bank?", ["treasury"]),
    ("Where is the Ministry of Housing located?", ["townhall, oysterdam", "townhall"]),
    ("What is Hendrikdam?", ["island"]),
    ("What is the name of the pope?", ["paul vii", "paulus"]),
    ("What color are the pope's eyes?", ["brown"]),
    ("What language is Stein und Eiche in?", ["german"]),
    ("What is the Wilhelmus?", ["anthem"]),
    ("who is bjorn", ["minister of defence", "veteran"]),
    ("what does the royal navy do", ["protect", "royal fleet", "ports"]),
    ("Who is the minister of housing?", ["cas"]),
    ("Who was Nicholas's father?", ["nicholas goudhof iv", "businessman"]),
    ("What nationality is the VAZ-2101?", ["russian"]),
    ("Which allied company does shipping?", ["imperial lines"]),
    ("What are the seven regions?", ["dunhag", "hendrikdam"]),
]
OOD = [
    "What is the capital of France?",
    "Who is the president of the United States?",
    "How do I bake a cake?",
    "What is the speed of light?",
]
